const api = window.location.pathname.startsWith('/apex/') ? '/apex' : '';
let accessToken = sessionStorage.getItem('apex_access_token');
const $ = (id) => document.getElementById(id);
let approvalId = null;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3000)}
async function request(path, options={}){const headers=new Headers(options.headers||{});if(accessToken)headers.set('Authorization',`Bearer ${accessToken}`);const target=path.startsWith('/auth/')?path:api+path;const response=await fetch(target,{...options,headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`Request failed: ${response.status}`)}return response}
$('login-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=new FormData(event.target);try{const response=await fetch('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:form.get('username'),password:form.get('password')})});if(!response.ok)throw new Error('Invalid username or password');const token=await response.json();accessToken=token.access_token;sessionStorage.setItem('apex_access_token',accessToken);const user=await request('/auth/me');$('login').hidden=true;$('workbench').hidden=false;$('session').textContent=`${user.username} / ${user.role}`;toast('Secure session started')}catch(error){toast(error.message)}});
$('show-login').addEventListener('click',()=>{$('login-form').hidden=false;$('register-form').hidden=true;$('show-login').classList.add('active');$('show-register').classList.remove('active')});
$('show-register').addEventListener('click',()=>{$('login-form').hidden=true;$('register-form').hidden=false;$('show-register').classList.add('active');$('show-login').classList.remove('active')});
$('register-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=new FormData(event.target);try{const response=await fetch('/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:form.get('username'),email:form.get('email'),password:form.get('password'),role:form.get('role')})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||'Registration failed')}event.target.reset();$('show-login').click();toast('Account created. Sign in to continue')}catch(error){toast(error.message)}});
$('upload-form').addEventListener('submit',async(event)=>{event.preventDefault();const file=$('file').files[0];if(!file)return;const data=new FormData(event.target);data.append('file',file);try{const response=await request('/documents/upload',{method:'POST',body:data});const result=await response.json();$('trust-result').hidden=false;$('trust-result').innerHTML=`<strong>${result.trust_score}/100</strong><p><b>${result.filename}</b><br>SHA-256: ${result.sha256}<br>Source: ${result.source}<br>Status: ${result.trust_status.toUpperCase()} / ${result.knowledge_base_status}</p>`;$('trust-badge').textContent='TRUSTED';$('trust-badge').className='badge';toast('Document scanned and fingerprinted')}catch(error){toast(error.message)}});
$('run').addEventListener('click',async()=>{const button=$('run');button.disabled=true;$('run-message').textContent='Planner and evidence services are running...';try{const response=await request('/analysis/run?asset_id=P101',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:$('question').value,limit:5})});const result=await response.json();approvalId=result.approval_id;$('analysis').hidden=false;$('observed').textContent=result.findings?.observed_value||'—';$('threshold').textContent=result.findings?.threshold||'—';$('model').textContent=result.model_used||'local';$('finding-title').textContent=result.findings?.issue||'Awaiting approval';$('risk').textContent=`${result.risk||'HIGH'} RISK`;$('trace').innerHTML=(result.agent_trace||[]).map(item=>`<li>${item}</li>`).join('');$('evidence').innerHTML=(result.findings?.sources||[]).map(source=>`<div><b>${source.document}</b>Page ${source.page} · ${source.trust_status}</div>`).join('');$('assets').innerHTML=(result.findings?.asset_relationships||[]).map(item=>`<div><b>${item.relationship}</b>${item.source} → ${item.target}</div>`).join('');$('report').hidden=true;$('run-message').textContent=result.interrupt?'Paused for human approval':result.approval_status;toast('Analysis paused safely for approval')}catch(error){toast(error.message);$('run-message').textContent=error.message}finally{button.disabled=false}});
async function loadReport(){const reportResponse=await request('/reports/download');const reportBlob=await reportResponse.blob();$('report').href=URL.createObjectURL(reportBlob);$('report').hidden=false}
async function decide(decision){if(!approvalId)return;try{const response=await request(`/approvals/${approvalId}/${decision}`,{method:'POST'});const result=await response.json();$('approval-text').textContent=`Human decision: ${result.status}`;$('approve').disabled=true;$('reject').disabled=true;if(result.workflow)await loadReport();toast(`Approval ${result.status.toLowerCase()}`)}catch(error){toast(error.message)}}
$('approve').addEventListener('click',()=>decide('approve'));$('reject').addEventListener('click',()=>decide('reject'));
